swagger: "2.0"
info:
  title: API de Notificaciones
  description: API para registrar usuarios y enviar notificaciones por canal preferido
  version: 1.0.0

paths:
  /:
    get:
      summary: Bienvenida a la API de notificaciones
      responses:
        200:
          description: Mensaje de bienvenida
          schema:
            type: object
            properties:
              message:
                type: string

  /users:
    post:
      summary: Registra un nuevo usuario
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              preferred_channel:
                type: string
              available_channels:
                type: array
                items:
                  type: string
      responses:
        201:
          description: Usuario registrado
        400:
          description: Error en la solicitud

    get:
      summary: Lista todos los usuarios registrados
      responses:
        200:
          description: Lista de usuarios
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                preferred_channel:
                  type: string
                channels:
                  type: array
                  items:
                    type: string

  /notifications/send:
    post:
      summary: Envia una notificacion a un usuario
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              user_id:
                type: string
              message:
                type: string
              priority:
                type: string
      responses:
        200:
          description: Resultado del envio
          schema:
            type: object
            properties:
              success:
                type: boolean
              channel_attempts:
                type: array
                items:
                  type: string
        400:
          description: Error en la solicitud
        404:
          description: Usuario no encontrado
